In [1]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
for i in arr:
    print(i)

1
2
3
4
5
6
7
8


In [10]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

for i in arr:
    print(i)

for k in arr:
    for l in k:
        print(l)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
1
2
3
4
5
6
7
8
9
10
11
12


In [16]:
arr = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])

print(arr)
print(arr.ndim)
print()

for i,d in np.ndenumerate(arr):
    print(i,d)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
3

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 6
(0, 1, 1) 7
(0, 1, 2) 8
(0, 1, 3) 9
(0, 1, 4) 10
(0, 2, 0) 11
(0, 2, 1) 12
(0, 2, 2) 13
(0, 2, 3) 14
(0, 2, 4) 15


In [18]:
arr = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])

print(arr)
print(arr.ndim)
print()

for i in np.nditer(arr):
    print(i)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
3

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
