In [9]:
import numpy as np

arr = np.array([1,2,3,4,5,6,2,7,2,8,9,2,10,2])

x = np.where(arr == 2)
print(x)

y = np.where(arr%2 == 0)
print(y)

(array([ 1,  6,  8, 11, 13], dtype=int64),)
(array([ 1,  3,  5,  6,  8,  9, 11, 12, 13], dtype=int64),)


In [19]:
arr = np.array([1,2,3,4,5,5,5,5,5,5,5,5,5,6,7,8,9,9,9,9,9,9])

x = np.searchsorted(arr,50)
print(x)
y = np.searchsorted(arr,5,side="right")
print(y)

22
13


In [25]:
arr = np.array([1,2,43,21,23,4,1,342,98,9876])
arr1 = np.array(["poiuyhg","eghjm","rtyhjbv","mnbvc","wedfghj"])
print(np.sort(arr))
print(np.sort(arr1))

[   1    1    2    4   21   23   43   98  342 9876]
['eghjm' 'mnbvc' 'poiuyhg' 'rtyhjbv' 'wedfghj']


In [29]:
arr = np.array([1,2,3,4,5,6])
x = [False,True,True,False,True,False]

ans = arr[x]
print(ans)

[2 3 5]
