In [8]:
import numpy as np

arr = np.array([[1,2,5,9] , [3,8,5,4]])
print(arr)
print(arr.shape)

[[1 2 5 9]
 [3 8 5 4]]
(2, 4)


In [14]:
arr1 = np.array([1,2,3,4,6] , ndmin=10)
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[[[[[[[[[[1 2 3 4 6]]]]]]]]]]
10
(1, 1, 1, 1, 1, 1, 1, 1, 1, 5)


In [3]:
import numpy as np

arr2 = np.array([1,2,3,4,5,6])
print(arr2)
print(arr2.ndim)

arr3 = arr2.reshape(3,2)
print(arr3)
print(arr3.ndim)

[1 2 3 4 5 6]
1
[[1 2]
 [3 4]
 [5 6]]
2


In [5]:
arr4 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr4)
print(arr4.ndim)

arr5 = arr4.reshape(2,3,2)
print(arr5)
print(arr5.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [7]:
arr4 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr4)
print(arr4.ndim)

arr5 = arr4.reshape(2,3,2)
print(arr5)
print(arr5.ndim)

arr6 = arr5.reshape(-1)
print(arr6)
print(arr6.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
