In [13]:
import numpy as np

arr = np.array([1253,8762,5473,513,6432,542,6514,8765,654,1234,6954,9876])

print(arr[2:6]) # from index: 2 to 5
print(arr[2:]) # from index: 2 to end
print(arr[:6]) # from start to index 5
print(arr[0:13:2])
print(arr[::2])

[5473  513 6432  542]
[5473  513 6432  542 6514 8765  654 1234 6954 9876]
[1253 8762 5473  513 6432  542]
[1253 5473 6432 6514  654 6954]
[1253 5473 6432 6514  654 6954]


In [15]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

print(arr[1,1:])

[6 7 8]
