In [3]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
np.random.shuffle(arr)
print(arr)

[1 6 2 4 3 5]


In [13]:
arr = np.array([1,2,2,3,4,5,2,3,4,7,7,8,9,9])
x = np.unique(arr)
y = np.unique(arr,return_index=True)
z = np.unique(arr,return_index=True,return_counts=True)
print(x)
print(y)
print(z)

[1 2 3 4 5 7 8 9]
(array([1, 2, 3, 4, 5, 7, 8, 9]), array([ 0,  1,  3,  4,  5,  9, 11, 12], dtype=int64))
(array([1, 2, 3, 4, 5, 7, 8, 9]), array([ 0,  1,  3,  4,  5,  9, 11, 12], dtype=int64), array([1, 3, 2, 2, 1, 2, 1, 2], dtype=int64))


In [15]:
arr = np.array([1,2,3,4,5,6,7,8])
x = np.resize(arr,(2,4))
print(x)

[[1 2 3 4]
 [5 6 7 8]]


In [21]:
arr = np.array([1,2,3,4,5,6,7,8])
x = np.resize(arr,(2,4))
print(x)
print()
print("Flatten: ",x.flatten(order="F"))
print()
print("Ravel: ",x.ravel(order="F"))

[[1 2 3 4]
 [5 6 7 8]]

Flatten:  [1 5 2 6 3 7 4 8]

Ravel:  [1 5 2 6 3 7 4 8]
