In [3]:
import numpy as np

arr1 = np.array([1,2,4,5,6])
arr2 = np.array([3,4,6,7])
# print(arr1+arr2) --> gives error

In [5]:
arr1 = np.array([1,2,4,5,6])
arr2 = np.array([[1],[2],[3],[4]])

print(arr1+arr2)

[[ 2  3  5  6  7]
 [ 3  4  6  7  8]
 [ 4  5  7  8  9]
 [ 5  6  8  9 10]]


In [18]:
arr1 = np.array([[1],[2],[3]])
print(arr1.shape)

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr1+arr2)

(3, 1)
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
