In [3]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([7,6,5,4,3])

arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 7 6 5 4 3]


In [11]:
arr1 = np.array([[1,2,3,4,5],[2,3,4,8,7]])
arr2 = np.array([[7,6,5,4,3],[1,76,23,76,2]])

arr_res1 = np.concatenate((arr1,arr2),axis=0)
arr_res2 = np.concatenate((arr1,arr2),axis=1)

print(arr_res1)
print(arr_res2)

[[ 1  2  3  4  5]
 [ 2  3  4  8  7]
 [ 7  6  5  4  3]
 [ 1 76 23 76  2]]
[[ 1  2  3  4  5  7  6  5  4  3]
 [ 2  3  4  8  7  1 76 23 76  2]]


In [23]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([7,6,5,4,3])

ans1 = np.hstack((arr1,arr2)) # row
ans2 = np.vstack((arr1,arr2)) # col
ans3 = np.dstack((arr1,arr2)) # height

print(ans1)
print(ans2)
print(ans3)

[1 2 3 4 5 7 6 5 4 3]
[[1 2 3 4 5]
 [7 6 5 4 3]]
[[[1 7]
  [2 6]
  [3 5]
  [4 4]
  [5 3]]]
