In [3]:
import numpy as np

variable_arr = np.random.rand(5) # rand --> numbers btw 0 and 1
print(variable_arr)

[0.63212561 0.482392   0.98193443 0.31053929 0.02472721]


In [7]:
variable_arr2 = np.random.rand(3,6)
print(variable_arr2)

[[0.31828656 0.44290103 0.85902539 0.1356525  0.3965349  0.29372858]
 [0.71610403 0.30769185 0.41078733 0.67647346 0.83349832 0.78640255]
 [0.81448415 0.19060323 0.13286823 0.09317791 0.05480196 0.37303779]]


In [9]:
variable_arr3 = np.random.randn(6) # close to 0 both +ve and -ve
print(variable_arr3)

[ 1.46627007  0.7111129  -1.54562451 -0.57589483 -0.38453534  2.80756177]


In [11]:
variable_arr4 = np.random.randn(3,6)
print(variable_arr4)

[[-0.31453069 -0.32688549  0.2135703  -1.60435081  1.61002676 -1.14835993]
 [ 1.29057678  0.5093551  -0.8695994   0.07342213 -1.73732889 -1.49479532]
 [-0.79432147 -0.38087132 -0.93399244 -0.71765288 -0.46744061  0.98613344]]


In [18]:
variable_arr5 = np.random.ranf(6) # [0.0 , 1.0)
print(variable_arr5)

[0.46409075 0.88018034 0.07624318 0.20871076 0.71517103 0.44657176]


In [26]:
variable_arr6 = np.random.ranf(18).reshape(6,3)
print(variable_arr6)

[[0.85979655 0.77119629 0.89914916]
 [0.77773029 0.41619495 0.90377998]
 [0.4885342  0.4600915  0.27927443]
 [0.13383361 0.45481635 0.34569046]
 [0.30268059 0.23084857 0.65433424]
 [0.57292561 0.35836307 0.97997449]]


In [28]:
variable_arr7 = np.random.randint(2,10,7) # (min,max,totalvalues)
print(variable_arr7)

[4 7 5 4 4 4 3]


In [30]:
variable_arr7 = np.random.randint(2,50,15).reshape(3,5)
print(variable_arr7)

[[ 6  3 22 38 24]
 [10 27  6  9 40]
 [27 15 25 40 39]]
