In [1]:
import numpy as np

arr = np.array([1098,1232,3123,245,526,767,835,999,543])

print(arr[0])
print(arr[7])
print(arr[-1])
print(arr[-2])

1098
999
543
999


In [13]:
arr = np.array([[1,2,3],[4,5,7],[11,24,53]])

print(arr[0])
print(arr[-1])
print(arr[-2,1])

[1 2 3]
[11 24 53]
5


In [15]:
arr = np.array([[[1,2,3],[6,7,8]]])

print(arr)
print(arr.ndim)
print(arr[0,0])
print(arr[0,1,2])

[[[1 2 3]
  [6 7 8]]]
3
[1 2 3]
8
