In [7]:
import numpy as np

arr_zero = np.zeros(4)
print(arr_zero)

arr_zero2 = np.zeros((3,4)) #  2D array with 3 rows and 4 cols
print()
print(arr_zero2)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
arr_ones = np.ones(7)
arr_ones2 = np.ones((6,3))

print(arr_ones)
print(arr_ones2)

[1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
arr_empty = np.empty(8)

print(arr_empty)

[4.67296746e-307 1.69121096e-306 4.22791195e-307 1.42419938e-306
 7.56603881e-307 8.45603440e-307 4.45046008e-307 2.37667058e-312]


In [21]:
arr_range = np.arange(8)

print(arr_range)

[0 1 2 3 4 5 6 7]


In [27]:
arr_diag = np.eye(6)
arr_diag2 = np.eye(3,5)

print(arr_diag)
print()
print(arr_diag2)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [29]:
arr_ls = np.linspace(0,20,num=5)

print(arr_ls)

[ 0.  5. 10. 15. 20.]
