In [1]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

print("Minimum element: ", np.min(arr))
print("Maximum element: ", np.max(arr))
print("Minimum element position: ", np.argmin(arr))
print("Maximum element position: ", np.argmax(arr))

Minimum element:  1
Maximum element:  8
Minimum element position:  0
Maximum element position:  7


In [9]:
arr = np.array([[1,2,3,4,5,6,7,98] , [9,10,11,12,13,14,15,16]])

print("Minimum element: ", np.min(arr,axis=0)) # axis = 0 --> col
print("Maximum element: ", np.max(arr,axis=1)) # axis = 1 --> row
print("Minimum element position: ", np.argmin(arr,axis=1))
print("Maximum element position: ", np.argmax(arr,axis=0))

Minimum element:  [ 1  2  3  4  5  6  7 16]
Maximum element:  [98 16]
Minimum element position:  [0 0]
Maximum element position:  [1 1 1 1 1 1 1 0]


In [15]:
arr = np.array([4,9,25,36,49,64])

print(np.sqrt(arr))

[2. 3. 5. 6. 7. 8.]


In [19]:
arr = np.array([0,30,45,60,90])

print(np.sin(arr))
print(np.cos(arr))
print(np.cumsum(arr)) # cumulative sum

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]
[  0  30  75 135 225]
