In [1]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
add_arr = arr + 5

print(arr)
print(add_arr)

[1 2 3 4 5 6]
[ 6  7  8  9 10 11]


In [3]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([10,22,37,44,25,60])

add_arr = arr1+arr2
print(arr1)
print(arr2)
print(add_arr)

[1 2 3 4 5 6]
[10 22 37 44 25 60]
[11 24 40 48 30 66]


In [5]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([10,22,37,44,25,60])

add_arr = arr1-arr2
print(arr1)
print(arr2)
print(add_arr)

[1 2 3 4 5 6]
[10 22 37 44 25 60]
[ -9 -20 -34 -40 -20 -54]


In [11]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([10,22,37,44,25,60])

add_arr = np.multiply(arr1,arr2)
# add_arr = arr1*arr2 --> also works

print(arr1)
print(arr2)
print(add_arr)

[1 2 3 4 5 6]
[10 22 37 44 25 60]
[ 10  44 111 176 125 360]
