In [9]:
import numpy as np

x = [1,2,3,4,5,6,7,8]
y = np.array(x)

print(x)
print(type(x))
print(y)
print(type(y))
print(y.ndim)

[1, 2, 3, 4, 5, 6, 7, 8]
<class 'list'>
[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>
1


In [3]:
l = []
for i in range(1,6):
    int_ip = input("enter value: ")
    l.append(int_ip)

print(np.array(l))
print(l[0])
print(type(l[0]))

enter value:  12
enter value:  23
enter value:  123
enter value:  43
enter value:  98


['12' '23' '123' '43' '98']
12
<class 'str'>


In [7]:
m = []
for i in range(1,6):
    int_ip = int(input("enter value: "))
    m.append(int_ip)

print(np.array(m))
print(m[0])
print(type(m[0]))

enter value:  43
enter value:  54
enter value:  65
enter value:  776
enter value:  876


[ 43  54  65 776 876]
43
<class 'int'>


In [17]:
arr2 = np.array([[1,2,3,4,5] , [6,7,8,9,10]])
print(arr2)
print(arr2.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


In [19]:
arrn = np.array([1,2,3,4,5] , ndmin = 10)
print(arrn)
print(arrn.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10
