In [5]:
import numpy as np

arr = np.array([1,2,3,4,5,7,9])
print(arr)

arr1 = np.array_split(arr,3)
print(arr1)
print(type(arr1))
print(arr1[0])

[1 2 3 4 5 7 9]
[array([1, 2, 3]), array([4, 5]), array([7, 9])]
<class 'list'>
[1 2 3]


In [11]:
arr = np.array([[1,2,3],[4,5,7],[13,23,9]])
print(arr)
print()

arr1 = np.array_split(arr,3,axis=1)
print(arr1)
print()
print(type(arr1))
print()
print(arr1[0])

[[ 1  2  3]
 [ 4  5  7]
 [13 23  9]]

[array([[ 1],
       [ 4],
       [13]]), array([[ 2],
       [ 5],
       [23]]), array([[3],
       [7],
       [9]])]

<class 'list'>

[[ 1]
 [ 4]
 [13]]
