In [11]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9])
arr_copy = arr.copy()

arr[3] = 999

print(arr)
print()
print(arr_copy)

[  1   2   3 999   5   6   7   8   9]

[1 2 3 4 5 6 7 8 9]


In [17]:
arr = np.array([31,42,53,84,85,63,75,82,90])
arr_view = arr.view()

arr[3] = 5678
arr_view[4] = 9876

print(arr)
print()
print(arr_view)

[  31   42   53 5678 9876   63   75   82   90]

[  31   42   53 5678 9876   63   75   82   90]
