In [1]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

print("Data Type: ", arr.dtype)

Data Type:  int32


In [3]:
arr = np.array([1.1,2,3,4.9,5.3,6,4,5.7,7.5])

print("Data Type: ", arr.dtype)

Data Type:  float64


In [5]:
arr = np.array(["kjhgf","poiuy","tyhg","bvcgh"])

print("Data Type: ", arr.dtype)

Data Type:  <U5


In [7]:
arr = np.array([1.1,2,3,4.9,5.3,6,4,5.7,7.5,"kjhgf","poiuy","tyhg","bvcgh"])

print("Data Type: ", arr.dtype)

Data Type:  <U32


In [11]:
arr = np.array([1,2,3,4,5,6], dtype = np.int8) # changing data type

print("Data Type: ", arr.dtype)

Data Type:  int8


In [13]:
arr = np.array([1,2,3,4,5,6] , dtype = "f")

print("Data Type: ", arr.dtype)

Data Type:  float32


In [17]:
arr1 = np.array([1,2,3,4,5,6,7,8,9]) 

newDataType = np.float32(arr1)

print("Data Type: ",arr1.dtype)
print("Data Type: ",newDataType.dtype)
print(arr1)
print(newDataType)


Data Type:  int32
Data Type:  float32
[1 2 3 4 5 6 7 8 9]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [21]:
arr1 = np.array([1,2,3,4,5,6,7,8,9]) 

newDataType = arr1.astype(float)

print("Data Type: ",arr1.dtype)
print("Data Type: ",newDataType.dtype)
print(arr1)
print(newDataType)


Data Type:  int32
Data Type:  float64
[1 2 3 4 5 6 7 8 9]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
