In [33]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])
print(arr)

arr1 = np.insert(arr,2,40)
print(arr1)

arr2 = np.insert(arr,(3,6),999)
print(arr2)

arr3 = np.append(arr,9.99)
print(arr3)

arr4 = np.delete(arr,6) # 6 is the index number of element to be deleted
print(arr4)

[1 2 3 4 5 6 7]
[ 1  2 40  3  4  5  6  7]
[  1   2   3 999   4   5   6 999   7]
[1.   2.   3.   4.   5.   6.   7.   9.99]
[1 2 3 4 5 6]


In [31]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

arr1 = np.insert(arr,1,99,axis=1)
print(arr1)

arr2 = np.insert(arr,1,99,axis=0)
print(arr2)

arr3 = np.insert(arr,1,[999,998,997],axis=0)
print(arr3)

arr4 = np.append(arr,[[10000,10001,10002]],axis=0)
print(arr4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1 99  2  3]
 [ 4 99  5  6]
 [ 7 99  8  9]]
[[ 1  2  3]
 [99 99 99]
 [ 4  5  6]
 [ 7  8  9]]
[[  1   2   3]
 [999 998 997]
 [  4   5   6]
 [  7   8   9]]
[[    1     2     3]
 [    4     5     6]
 [    7     8     9]
 [10000 10001 10002]]
