In [9]:
import numpy as np

arr1 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print(type(arr1))

print()

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
print(type(arr2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.matrix'>

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [15]:
arr1 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.matrix([[15,27,93],[74,35,69],[70,88,92]])

print(arr1+arr2)
print()

print(arr1-arr2)
print()

print(arr1*arr2)
print()


[[ 16  29  96]
 [ 78  40  75]
 [ 77  96 101]]

[[-14 -25 -90]
 [-70 -30 -63]
 [-63 -80 -83]]

[[ 373  361  507]
 [ 850  811 1269]
 [1327 1261 2031]]


In [39]:
arr = np.matrix([[1,2,3],[1,2,9],[7,8,9]])

print(arr)
print()

print(np.transpose(arr))
print()
print(arr.T)
print()
print(np.swapaxes(arr,0,1))
print()

print(np.linalg.inv(arr))
print()

print(np.linalg.matrix_power(arr,3))
print()

print(np.linalg.det(arr))

[[1 2 3]
 [1 2 9]
 [7 8 9]]

[[1 1 7]
 [2 2 8]
 [3 9 9]]

[[1 1 7]
 [2 2 8]
 [3 9 9]]

[[1 1 7]
 [2 2 8]
 [3 9 9]]

[[-1.5         0.16666667  0.33333333]
 [ 1.5        -0.33333333 -0.16666667]
 [-0.16666667  0.16666667 -0.        ]]

[[ 390  492  774]
 [ 858 1104 1818]
 [1398 1752 2718]]

36.0
